### ISSUE TITLE
tokenify-0.1.0.0 release tarball incomplete

### ISSUE THREAD

**Issue by peti** [AKST/tokenify#1]
The package does not compile. Citing from http://hydra.cryp.to/build/853837/log/raw:

```
Preprocessing library tokenify-0.1.0.0...

src/Text/Tokenify.hs:25:8:
    Could not find module ‘Text.Tokenify.Response’
    Use -v to see a list of the files searched for.

src/Text/Tokenify.hs:26:8:
    Could not find module ‘Text.Tokenify.CharSeq’
    Use -v to see a list of the files searched for.

src/Text/Tokenify.hs:27:8:
    Could not find module ‘Text.Tokenify.Regex’
    Use -v to see a list of the files searched for.
```

**Comment by AKST** [comment]
Thanks for the heads up, I'll investigate. This is my first package on hackage so I might be missing something that's obvious to long time users

**Comment by AKST** [comment]
Looks like I misunderstood the purpose of [exposed modules](https://github.com/AKST/tokenify/blob/6944c4f3a79dc05d8190597ed9e3a2dc7ef70b79/tokenify.cabal#L16) field in the cabal package file.

I was thinking that if I omit a module name from that field, the module would be inaccessible to library users via imports. _Turns out this is true, but only because the library no longer compiles_.

I don't want the constructors accessible to users of the library for API purposes, but I would like the libraries accessible to other modules within this package. I'm going to look for a solution either way, but if you have any recommended approaches to achieve this feel free to suggest them .

**Comment by AKST** [comment]
Okay found out it's `other-modules`, will push changes

**Comment by AKST** [comment]
I was able to install the library, so I'll close the issue. 

Thanks again for bringing this to my attention
